Online-shop-Template/Models/Order.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Online_shop_Template.Models
{
    public class Order
    {
        [Key]
        public int Id { get; set; }

        public string Email { get; set; }

        public string? CheckoutId { get; set; }//set as nullable for webhooks.
        public string? OrderPaid { get; set; }//set as nullable for webhooks.
        public string UserId { get; set; }
        [ForeignKey(nameof(UserId))]
        public ApplicationUser User { get; set; }

        public List<OrderItem> OrderItems { get; set; }
    }

}

Online-shop-Template/Controllers/OrdersController.cs
using Online_shop_Template.Data.Cart;
using Online_shop_Template.Data.Services;
using Online_shop_Template.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Online_shop_Template.Models;
using Stripe;
using Stripe.Checkout;
using Microsoft.Extensions.Options;
using System.Diagnostics;
using Microsoft.AspNetCore.Identity;



namespace Online_shop_Template.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IProductService _productService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrderService _orderService;
        private readonly StripeSettings _stripeSettings;
        private readonly IConfiguration _configuration;
        private readonly UserManager<ApplicationUser> _userManager;

        public OrdersController(IConfiguration configuration, UserManager<ApplicationUser> userManager, IProductService productsService, ShoppingCart shoppingCart, IOrderService ordersService, IOptions<StripeSettings> stripeSettings)
        {
            _configuration = configuration;
            _productService = productsService;
            _shoppingCart = shoppingCart;
            _orderService = ordersService;
            _stripeSettings = stripeSettings.Value;
            _userManager = userManager;
        }
        
        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _orderService.GetOrdersByUserIdAndRoleAsync(userId, userRole);

            return View(orders);
        }

        public IActionResult CreateCheckoutSession(float amount)
        {
            var currency = "gbp"; // Currency code
            var successUrl = "https://localhost:7027/Orders/Index";
            var cancelUrl = "https://localhost:7027/Orders/ShoppingCart";
            StripeConfiguration.ApiKey = _stripeSettings.SecretKey;
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var options = new SessionCreateOptions
            {
                PaymentMethodTypes = new List<string>
                {
                    "card"
                },
                LineItems = new List<SessionLineItemOptions>
                {
                    new SessionLineItemOptions
                    {
                        PriceData = new SessionLineItemPriceDataOptions
                        {
                            Currency = currency,
                            UnitAmount = Convert.ToInt32(amount) * 100,  // Amount in smallest currency unit (e.g., cents)
                            ProductData = new SessionLineItemPriceDataProductDataOptions
                            {
                                Name = "Product Name",
                                Description = "Product Description"
                            }
                        },
                        Quantity = 1
                    }
                },
                Mode = "payment",
                SuccessUrl = successUrl,
                CancelUrl = cancelUrl,
                Metadata = new Dictionary<string, string>
                {
                    { "UserId", userId.ToString() },
                    { "UserRole", userRole.ToString() },
                    
                }
            };
            var service = new SessionService();
            var session = service.Create(options);

            CompleteOrder(session.Id).GetAwaiter().GetResult(); 

            return Redirect(session.Url);
        }
        public async Task<IActionResult> Success()
        {
            return View("OrderCompleted");
        }
        public IActionResult Cancel()
        {
            return View("Index");
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _productService.GetProductByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _productService.GetProductByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        
        public async Task<IActionResult> CompleteOrder(string checkOutId)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);            
            
            await _orderService.StoreOrder(items, userId, userEmailAddress, checkOutId);
             
            await _shoppingCart.ClearShoppingCartAsync();    

            return View("OrderCompleted");
        }



    }
}

Online-shop-Template/Controllers/ProductController.cs
using Online_shop_Template.Data;
using Online_shop_Template.Data.Services;
using Online_shop_Template.Data.Static;
using Online_shop_Template.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.SqlServer.Management.Smo.Wmi;

namespace Online_shop_Template.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ProductController : Controller
    {
        
        private readonly IProductService _service;

        public ProductController(IProductService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allProducts = await _service.GetAllAsync();
            return View(allProducts);
        }

        // For searching movies, 
        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var allProducts = await _service.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allProducts.Where(n => n.Name.ToLower().Contains(searchString.ToLower()) || n.Description.ToLower().Contains(searchString.ToLower())).ToList();

                //var filteredResultNew = allMovies.Where(n => string.Equals(n.Name, searchString, StringComparison.CurrentCultureIgnoreCase) || string.Equals(n.Description, searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();

                return View("Index", filteredResult);
            }

            return View("Index", allProducts);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var productdetail = await _service.GetProductByIdAsync(id);
                return View(productdetail);
        }

        public async Task<IActionResult> Create()
        {
            var movieDropdownsData = await _service.GetNewProductDropdownsVMValues();
            //ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            //ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            //ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View();     
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewProductVM product)
        {
            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _service.GetNewProductDropdownsVMValues();

                //ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
                //ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
                //ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

                return View(product);
            }

            await _service.AddNewProductAsync(product);
            return RedirectToAction(nameof(Index));
        }

        //GET: Movies/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var productDetails = await _service.GetProductByIdAsync(id);
            if (productDetails == null) return View("NotFound");

            var response = new NewProductVM()
            {
                Id = productDetails.Id,
                Name = productDetails.Name,
                Description = productDetails.Description,
                Price = productDetails.Price,
                StartDate = productDetails.StartDate,
                EndDate = productDetails.EndDate,
                ImageURL = productDetails.ImageURL,
                
            };

            var productDropdownsData = await _service.GetNewProductDropdownsVMValues();
            

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewProductVM product)
        {
            if (id != product.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _service.GetNewProductDropdownsVMValues();

                return View(product);
            }

            await _service.UpdateProductAsync(product);
            return RedirectToAction(nameof(Index));
        }

        //Get: product/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var productDetails = await _service.GetByIdAsync(id);
            if (productDetails == null) return View("NotFound");
            return View(productDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var productDetails = await _service.GetByIdAsync(id);
            if (productDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Online-shop-Template/Views/Orders/Index.cshtml
@model List<Order>

@{ 
    ViewData["Title"] = "All orders";
}

<p>
    <h4 class="text-light">List of all your orders</h4>
</p>

<table id="myTable" class="table text-light" style="max-width:90%;overflow-x:auto;font-weight:bold">
    <thead>
        <tr>
            <th>Order ID</th>
            <th>Items</th>
            <th>Total</th>
            <th>Status</th>
            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                <th>User</th>
                <th>Address</th>
            }

        </tr>
    </thead>
    <tbody>
        @foreach (var order in Model)
        {
        <tr>
            <td class="align-middle">@order.Id</td>
            <td class="align-middle">
                <ul style="list-style-type:none">
                    @foreach (var item in order.OrderItems)
                    {
                        <li>
                            <span class="badge bg-primary">@item.Amount</span> [@item.Price.ToString("c")] - @item.Product.Name                           
                        </li>
                    }
                </ul>
            </td>
            <td class="align-middle">
                @order.OrderItems.Select(m => m.Product.Price * m.Amount).Sum().ToString("c")
            </td>                   
            <td class="align-middle" id="mytd">@order.OrderPaid</td>                
                
            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                <td class="align-middle"> @order.User.FullName </td>
                <td class="align-middle"> @order.User.Address </td>

            }
            </tr>
        }
    </tbody>
</table>


<script>
    // Get the table element
    var table = document.getElementById("myTable");

    // Loop through each row
    for (var i = 0, row; row = table.rows[i]; i++) {
        // Access the specific column (e.g., fourth column)
        var cell = row.cells[3];

        // Check the condition 
        if (cell.innerText === "Status") {
            cell.style.backgroundColor = "black";
        }
        else if (cell.innerText === "paid") {
            cell.style.backgroundColor = "darkgreen";
            cell.style.color = "black";
            
        }
        else {
            cell.style.backgroundColor = "darkred";
            cell.style.Color = "white";
            
        }
    }
</script>

Online-shop-Template/Views/Orders/OrderCompleted.cshtml
<div class="container text-light" style="max-width:700px;">    
    <h2>Order completed successfully</h2>
    <p>You can check all your orders in the Orders section of your profile</p>
    <a class="btn btn-primary text-white" asp-controller="Orders" asp-action="Index" style="border-radius:3px; margin:10px; padding:10px;">
        <i class="bi bi-cart-plus"></i> Return To Orders
    </a>
    <hr />
    <p>Thank you!</p>    
</div>

Online-shop-Template/Views/Orders/ShoppingCart.cshtml
@using Online_shop_Template.Data.ViewModels;
@using System.Web

@model ShoppingCartVM


@{
    ViewData["Title"] = "Shopping cart summary";
}


<div class="text-center text-light">
    <h2>Your Basket summary</h2>
</div>

<table class="text-light" style="width: 100%; overflow-x: auto; color:white">
        
        <tr>
            <th>Selected amount</th>
            <th>Product</th>
            <th>Price</th>
            <th>Subtotal</th>
            <th></th>
        </tr>
        
        
        @foreach (var item in Model.ShoppingCart.ShoppingCartItems)
        {
            <tr>
                <td>@item.Amount</td>
                <td>@item.Product.Name</td>
                <td>@item.Product.Price.ToString("c")</td>
                <td>@((item.Amount * item.Product.Price).ToString("c"))</td>
                <td style="text-align: center;">
                    <a class="text-danger" asp-controller="Orders" asp-action="RemoveItemFromShoppingCart"
                        asp-route-id="@item.Product.Id">
                        <i class="bi bi-cart-dash"></i>
                    </a>
                    |   |
                    <a class="text-success" asp-controller="Orders" asp-action="AddItemToShoppingCart"
                        asp-route-id="@item.Product.Id">
                        <i class="bi bi-cart-plus"></i>
                    </a>
                </td>
            </tr>
        }
        
    <tfoot>
        <tr>
            <td colspan="2"></td>
            <td><b class="text-light">Total:</b></td>
            <td class="text-light" >
                @Model.ShoppingCartTotal.ToString("c")
            </td>
            <td></td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <div class="btn-group">
        <a class="btn btn-outline-primary" asp-action="CompleteOrder">
        Complete order
        </a>
        <span style="padding:5px"></span>
        <a class="btn btn-success text-white" asp-controller="Product" asp-action="Index" style="border-radius:3px; margin:10px; padding:10px;">
            <i class="bi bi-cart-plus"></i> Add more items
        </a>

        <span style="padding:5px"></span>

        <form method="post" action="/Orders/CreateCheckoutSession">
            <!-- Form fields -->
            <div>
                <input type="hidden" id="amount" name="amount" value="@Model.ShoppingCartTotal" />
            </div>
            <!-- Submit button -->
            <button type="submit" id="amount" name="amount" class="btn btn-primary" style="padding:10px;margin:10px;">
                Checkout
                <i class="bi bi-apple"></i>
                <i class="bi bi-google"></i>
                <i class="bi bi-bi bi-credit-card-fill"></i>
                <i class="bi bi-paypal"></i>
            </button>
        </form>
        
    </div>
</div>